import type { AppLocale } from '../localization';
import type { ReportKind } from './types';

type ReportLabels = {
  technicalTitle: string;
  executiveTitle: string;
  generatedBy: string;
  project: string;
  repository: string;
  scannedAt: string;
  summary: string;
  totalFindings: string;
  codeFindings: string;
  dependencyFindings: string;
  high: string;
  medium: string;
  low: string;
  codeSection: string;
  dependenciesSection: string;
  severity: string;
  category: string;
  location: string;
  description: string;
  risk: string;
  fix: string;
  cve: string;
  package: string;
  affectedVersions: string;
  fixedIn: string;
  exploitLikely: string;
  priority: string;
  noCodeFindings: string;
  noDependencyFindings: string;
  semgrepStatus: string;
  executiveIntro: string;
  executiveOverview: string;
  executivePriorities: string;
  executiveNextSteps: string;
  executiveImpactHigh: string;
  executiveImpactMedium: string;
  executiveImpactLow: string;
  executiveNoIssues: string;
  executiveGlossaryTitle: string;
  executiveGlossaryCve: string;
  executiveGlossarySeverity: string;
  confidentialNotice: string;
};

const en: ReportLabels = {
  technicalTitle: 'Technical Security Report',
  executiveTitle: 'Executive Security Summary',
  generatedBy: 'Generated by Scout',
  project: 'Project',
  repository: 'Repository',
  scannedAt: 'Scan date & time',
  summary: 'Summary',
  totalFindings: 'Total findings',
  codeFindings: 'Code findings',
  dependencyFindings: 'Dependency findings',
  high: 'High',
  medium: 'Medium',
  low: 'Low',
  codeSection: 'Code findings',
  dependenciesSection: 'Dependency vulnerabilities',
  severity: 'Severity',
  category: 'Category',
  location: 'Location',
  description: 'Description',
  risk: 'Risk',
  fix: 'Recommended fix',
  cve: 'CVE',
  package: 'Package',
  affectedVersions: 'Affected versions',
  fixedIn: 'Fixed in',
  exploitLikely: 'Exploit likely',
  priority: 'Priority score',
  noCodeFindings: 'No code security findings were detected.',
  noDependencyFindings: 'No dependency vulnerabilities were reported.',
  semgrepStatus: 'Semgrep status',
  executiveIntro:
    'This summary explains the security review results in plain language for stakeholders who need the big picture without deep technical detail.',
  executiveOverview: 'Overall picture',
  executivePriorities: 'Top priorities',
  executiveNextSteps: 'Recommended next steps',
  executiveImpactHigh:
    'Critical issues were found that could allow attackers to steal data, take over accounts, or run malicious code. Address these as soon as possible.',
  executiveImpactMedium:
    'Important security weaknesses were found. They should be planned into the next development cycle before they become easier to exploit.',
  executiveImpactLow:
    'Minor security improvements were identified. They are worth fixing, but they are not an emergency on their own.',
  executiveNoIssues:
    'No significant security issues were detected in this scan. Continue regular updates and periodic reviews.',
  executiveGlossaryTitle: 'Quick glossary',
  executiveGlossaryCve:
    'CVE — a publicly known flaw in a software library. Attackers may use it if the library is outdated.',
  executiveGlossarySeverity:
    'Severity — how serious a finding is if exploited (High = urgent, Medium = plan a fix, Low = improve when convenient).',
  confidentialNotice:
    'This report may contain sensitive security details. Share only with people who need to act on it.'
};

const uk: ReportLabels = {
  technicalTitle: 'Технічний звіт з безпеки',
  executiveTitle: 'Зведений звіт для керівництва',
  generatedBy: 'Згенеровано Scout',
  project: 'Проєкт',
  repository: 'Репозиторій',
  scannedAt: 'Дата й час перевірки',
  summary: 'Підсумок',
  totalFindings: 'Усього знахідок',
  codeFindings: 'Знахідки в коді',
  dependencyFindings: 'Знахідки в залежностях',
  high: 'Високий',
  medium: 'Середній',
  low: 'Низький',
  codeSection: 'Знахідки в коді',
  dependenciesSection: 'Вразливості в залежностях',
  severity: 'Рівень загрози',
  category: 'Категорія',
  location: 'Розташування',
  description: 'Опис',
  risk: 'Ризик',
  fix: 'Рекомендоване виправлення',
  cve: 'CVE',
  package: 'Пакет',
  affectedVersions: 'Уразливі версії',
  fixedIn: 'Виправлено в',
  exploitLikely: 'Ймовірний exploit',
  priority: 'Пріоритет',
  noCodeFindings: 'Вразливостей у коді не виявлено.',
  noDependencyFindings: 'Вразливостей у залежностях не знайдено.',
  semgrepStatus: 'Статус Semgrep',
  executiveIntro:
    'Це зведення пояснює результати перевірки простою мовою для тих, кому потрібна загальна картина без глибоких технічних деталей.',
  executiveOverview: 'Загальна картина',
  executivePriorities: 'Головні пріоритети',
  executiveNextSteps: 'Рекомендовані наступні кроки',
  executiveImpactHigh:
    'Виявлено критичні проблеми, через які зловмисники можуть викрасти дані, захопити облікові записи або виконати шкідливий код. Виправте їх якомога швидше.',
  executiveImpactMedium:
    'Знайдено важливі слабкості безпеки. Їх варто запланувати в найближчому циклі розробки, поки їх не стало легше використати.',
  executiveImpactLow:
    'Виявлено незначні покращення безпеки. Їх варто виправити, але це не екстрена ситуація.',
  executiveNoIssues:
    'У цій перевірці суттєвих проблем безпеки не виявлено. Продовжуйте регулярні оновлення та періодичні огляди.',
  executiveGlossaryTitle: 'Короткий глосарій',
  executiveGlossaryCve:
    'CVE — відома вразливість у програмній бібліотеці. Її можуть використати, якщо бібліотека застаріла.',
  executiveGlossarySeverity:
    'Рівень загрози — наскільки серйозна знахідка при експлуатації (Високий = терміново, Середній = запланувати виправлення, Низький = коли зручно).',
  confidentialNotice:
    'Цей звіт може містити чутливі дані про безпеку. Діліться лише з тими, хто має на них реагувати.'
};

export const getReportLabels = (locale: AppLocale): ReportLabels => (locale === 'uk' ? uk : en);

export const getReportTitle = (kind: ReportKind, locale: AppLocale): string => {
  const labels = getReportLabels(locale);
  return kind === 'technical' ? labels.technicalTitle : labels.executiveTitle;
};
